"""empty message

Revision ID: 16d76f71f963
Revises: 5d6bcb659af7
Create Date: 2020-10-13 16:06:14.940318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16d76f71f963'
down_revision = '5d6bcb659af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('black_list')
    op.drop_index('ix_token_session_identity', table_name='token_session')
    op.drop_table('token_session')
    op.add_column('permission', sa.Column('entity_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'entity_type')
    op.create_table('token_session',
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expire_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('identity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_session_pkey'),
    sa.UniqueConstraint('token', name='token_session_token_key')
    )
    op.create_index('ix_token_session_identity', 'token_session', ['identity'], unique=False)
    op.create_table('black_list',
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('identity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='black_list_pkey')
    )
    # ### end Alembic commands ###
