"""add4

Revision ID: 5d6bcb659af7
Revises: 64f830ba2296
Create Date: 2020-09-15 13:23:47.077668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6bcb659af7'
down_revision = '64f830ba2296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'endpoint', 'service', ['service_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'endpoint', ['endpoint_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'method', ['method_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'user_groups', 'users', ['user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'user_groups', 'groups', ['group_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'endpoint', type_='foreignkey')
    # ### end Alembic commands ###
