"""add3

Revision ID: 64f830ba2296
Revises: 
Create Date: 2020-09-15 13:23:12.634076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
# revision identifiers, used by Alembic.
revision = '64f830ba2296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('identity', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoint',
    sa.Column('service_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_table('method',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_method_name'), 'method', ['name'], unique=False)
    op.create_table('permission',
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('method_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('endpoint_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_name'), 'service', ['name'], unique=False)
    op.create_table('token_session',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('identity', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_token_session_identity'), 'token_session', ['identity'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('group_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('identity', sa.String(), nullable=False),
    sa.Column('claim', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_identity'), 'users', ['identity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_identity'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_token_session_identity'), table_name='token_session')
    op.drop_table('token_session')
    op.drop_index(op.f('ix_service_name'), table_name='service')
    op.drop_table('service')
    op.drop_table('permission')
    op.drop_index(op.f('ix_method_name'), table_name='method')
    op.drop_table('method')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('endpoint')
    op.drop_table('black_list')
    # ### end Alembic commands ###
