"""empty message

Revision ID: 916c806e3c88
Revises: 61a914592175
Create Date: 2021-06-06 16:48:40.336405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916c806e3c88'
down_revision = '61a914592175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'endpoint', 'service', ['service_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'endpoint', ['endpoint_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'service', ['service_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'method', ['method_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'user_groups', 'users', ['user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'user_groups', 'groups', ['group_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'endpoint', type_='foreignkey')
    # ### end Alembic commands ###
