"""empty message

Revision ID: d973559d0863
Revises: a9cd7ffa44a1
Create Date: 2021-06-06 14:20:48.956503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd973559d0863'
down_revision = 'a9cd7ffa44a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'endpoint', 'service', ['service_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'endpoint', ['endpoint_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'service', ['service_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'method', ['method_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'user_groups', 'users', ['user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'user_groups', 'groups', ['group_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'endpoint', type_='foreignkey')
    # ### end Alembic commands ###
