"""empty message

Revision ID: df738f28e3df
Revises: 0c2cca0c918b
Create Date: 2021-06-15 18:13:48.620951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df738f28e3df'
down_revision = '0c2cca0c918b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_session',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('identity', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_token_session_identity'), 'token_session', ['identity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_session_identity'), table_name='token_session')
    op.drop_table('token_session')
    # ### end Alembic commands ###
