"""add service_id to permissions

Revision ID: e960ee62a77d
Revises: ba7be3d0f054
Create Date: 2021-05-11 18:47:19.723350

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e960ee62a77d'
down_revision = 'ba7be3d0f054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('service_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False))
    op.create_unique_constraint('uix_permission_entity_entity_type_method_id_endpoint_id', 'permission', ['entity', 'entity_type', 'method_id', 'endpoint_id'])
    op.create_foreign_key(None, 'permission', 'service', ['service_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint('uix_permission_entity_entity_type_method_id_endpoint_id', 'permission', type_='unique')
    op.drop_column('permission', 'service_id')
    # ### end Alembic commands ###
