"""entity enum type

Revision ID: ed30dc300261
Revises: 5d6bcb659af7
Create Date: 2020-09-15 17:35:31.126334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed30dc300261'
down_revision = '5d6bcb659af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    entityenum = postgresql.ENUM('active', 'inactive', 'archive', name='entityenum')
    entityenum.create(op.get_bind())

    op.add_column('permission', sa.Column('entity_type', postgresql.ENUM('user', 'group', 'service', name='entityenum'), nullable=True, use_alter=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    entityenum = postgresql.ENUM('active', 'inactive', 'archive', name='entityenum')
    entityenum.drop(op.get_bind())

    op.drop_column('permission', 'entity_type')
    # ### end Alembic commands ###
