"""service model name field unique=True

Revision ID: f4a0bfaf5fc7
Revises: 16d76f71f963
Create Date: 2020-10-14 03:35:41.003964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a0bfaf5fc7'
down_revision = '16d76f71f963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_name', table_name='service')
    op.create_index(op.f('ix_service_name'), 'service', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_name'), table_name='service')
    op.create_index('ix_service_name', 'service', ['name'], unique=False)
    # ### end Alembic commands ###
